//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.06 at 11:31:09 AM CET 
//


package org.languagetool.configuration;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.languagetool.configuration package. 
 * <p>An LTObjectFactory allows you to programatically
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class LTObjectFactory {


    /**
     * Create a new LTObjectFactory that can be used to create new instances of schema derived classes for package: org.languagetool.configuration
     * 
     */
    public LTObjectFactory() {
    }

    /**
     * Create an instance of {@link Ltconfiguration }
     * 
     */
    public Ltconfiguration createLtconfiguration() {
        return new Ltconfiguration();
    }

    /**
     * Create an instance of {@link GrammarType }
     * 
     */
    public GrammarType createGrammarType() {
        return new GrammarType();
    }

    /**
     * Create an instance of {@link MorfologikType }
     * 
     */
    public MorfologikType createMorfologikType() {
        return new MorfologikType();
    }

    /**
     * Create an instance of {@link RulefilesType }
     * 
     */
    public RulefilesType createRulefilesType() {
        return new RulefilesType();
    }

    /**
     * Create an instance of {@link RulefileType }
     * 
     */
    public RulefileType createRulefileType() {
        return new RulefileType();
    }

}
